# Generated by Django 5.0 on 2023-12-18 22:08

import OxigenoGYMAPP.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('apodo', models.CharField(blank=True, max_length=50)),
                ('fecha_inicio_cuota', models.DateField(blank=True, default=OxigenoGYMAPP.models.default_fecha_inicio, null=True)),
                ('fecha_fin_cuota', models.DateField(blank=True, default=OxigenoGYMAPP.models.default_fecha_fin, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuotaHistorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_cuota', models.DateField()),
                ('fecha_fin_cuota', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OxigenoGYMAPP.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'fecha_inicio_cuota', 'fecha_fin_cuota')},
            },
        ),
    ]
