# Generated by Django 5.0 on 2023-12-17 22:05

import OxigenoGYMAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OxigenoGYMAPP', '0002_cliente_fecha_fin_cuota_cliente_fecha_inicio_cuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_fin_cuota',
            field=models.DateField(blank=True, default=OxigenoGYMAPP.models.default_fecha_fin, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_inicio_cuota',
            field=models.DateField(blank=True, default=OxigenoGYMAPP.models.default_fecha_inicio, null=True),
        ),
    ]
