# Generated by Django 5.0 on 2024-01-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OxigenoGYMAPP', '0007_alter_producto_imagen1_alter_producto_imagen2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen3',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
